{
 "title": "Service Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Service Status",
   "type": "table",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "aggregator": "none",
     "alias": "$tag_url",
     "downsampleAggregator": "last",
     "downsampleFillPolicy": "zero",
     "downsampleInterval": "3m",
     "metric": "telegraf.ping.ping_average_response_ms"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 14, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "dtdurationms" }
   ],
   "targets": [
    {
     "aggregator": "none",
     "alias": "$tag_url",
     "downsampleAggregator": "max",
     "downsampleFillPolicy": "null",
     "downsampleInterval": "1m",
     "metric": "telegraf.ping.ping_average_response_ms"
    }
   ]
  },
  {
   "title": "TTL",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "none",
     "alias": "$tag_url",
     "downsampleAggregator": "max",
     "downsampleFillPolicy": "null",
     "downsampleInterval": "1m",
     "metric": "telegraf.ping.ping_ttl"
    }
   ]
  },
  {
   "title": "Packet Loss",
   "type": "graph",
   "gridPos": { "h": 5, "w": 14, "x": 10, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "aggregator": "none",
     "alias": "$tag_url",
     "downsampleAggregator": "max",
     "downsampleFillPolicy": "null",
     "downsampleInterval": "1m",
     "metric": "telegraf.ping.ping_percent_packet_loss"
    }
   ]
  }
 ]
}